listen_port: 8384

settings:
  gui:
    # by default syncthing only listens on localhost
    # this makes it listen on all ips
    - setting: config gui raw-address
      desired: "[::]:{{ listen_port }}"
      overrides:
        # we'll keep laptop gui only on localhost
        leorio.local: "127.0.0.1:{{ listen_port }}"
    - setting: config gui raw-use-tls
      desired: "true"
    - setting: config gui user
      desired: "{{ syncthing.gui_user }}"
    - setting: config gui password
      desired: "{{ syncthing.gui_password }}"
    - setting: config gui apikey
      desired: "{{ syncthing.gui_apikey }}"
  folders:
