[global]
    multicast dns register = yes
    fruit:metadata = stream
    fruit:encoding = native
    fruit:zero_file_id = yes
    fruit:nfs_aces = no
    fruit:aapl = yes

    client max protocol = default
    client min protocol = SMB2_02
    server max protocol = SMB3
    server min protocol = SMB2_02
    # wolfgang's channel
    # create mask = 0644
    # directory mask = 0755
    # time machine backup guide
    # inherit permissions = yes

    # defaults
    # create mask = 0744
    # directory mask = 0755
    # inherit permissions = no


[macos-backups]
    path = /mnt/spinners/macos-backups
    guest ok = no
    comment = for backing up mac computers
    browseable = yes
    read only = no
    writable = yes
    fruit:time machine = yes
    vfs objects = catia fruit streams_xattr aio_pthread

[spinners-data]
    path = /mnt/spinners/data
    guest ok = no
    comment = data to store on the hard drives
    browseable = yes
    read only = no
    writable = yes
    vfs objects = catia fruit streams_xattr aio_pthread

[theflash-data]
    path = /mnt/theflash/data
    guest ok = no
    comment = data to store on the hard drives
    browseable = yes
    read only = no
    writable = yes
    vfs objects = catia fruit streams_xattr aio_pthread
