#!/usr/bin/env bash
set -euo pipefail

if [[ -z "${ANSIBLE_VAULT_PASSWORD:-}" ]]; then
  # rather than fail we just return the wrong password.
  # this lets ansible run playbooks and commands that don't require the vault
  # without specifying the vault password.
  printf 'invalid password'
else
  printf '%s' "$ANSIBLE_VAULT_PASSWORD"
fi
