- name: include vault
  include_vars: "{{ playbook_dir }}/vault/vault.yml"

- name: RouterOS test with API
  block:
    - name: Gather facts
      community.routeros.api_facts:

    - name: bridge port
      community.routeros.api:
        path: interface bridge port

    - name: bridge vlan
      community.routeros.api:
        path: interface bridge vlan

    # access ports are configured with interface bridge port
    # they are automatically added to interface bridge vlan
    # when you set pvid=num
    - name: bridge port
      community.routeros.api_modify:
        path: interface bridge port
        data: "{{ bridge_port }}"

    # interface bridge vlan is how you configure trunk ports.
    # access ports are automatically added to this config
    # when you set them up with interface bridge port
    - name: bridge vlan modify
      community.routeros.api_modify:
        path: interface bridge vlan
        data: "{{ bridge_vlan }}"
